project:
  type: website
  resources:
    - img/*


website:
  title: "Spatial Data Science across Languages"
  navbar:
    title: false
    logo: img/sdsl-logo.png
    repo-actions: [issue]
    left:
      - href: index.qmd
        text: Home
      - workshops.qmd
      - reports.qmd
      - governance.qmd
  page-footer:
    center:
      - text: "Copyright 2025, SDSL Community"
    right:
      - icon: github
        href: "https://github.com/spatial-data-science"
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



